name: Build and Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

env:
  FIREBASE_PROJECTID: giftme-8e917

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Snap Config
        uses: antfu/action-write-config
        with:
          # the file path to be saved, yaml is also supported
          path: 'src/firebase/fbConfig.json'
          # can be an object
          data: 
            apiKey: '${{ secrets.FIREBASE_APIKEY }}'
            projectId: '${{ env.FIREBASE_PROJECTID }}'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: app
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: app
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ env.FIREBASE_PROJECTID }}
