name: Build and Deploy
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

env:
  FIREBASE_PROJECTID: giftme-8e917

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: create env file
        run: |
          touch .env
          echo API_KEY=${{ secrets.FIREBASE_APIKEY }} >> .env
          echo PROJECT_ID=${{ env.FIREBASE_PROJECTID }} >> .env
          cat .env
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: app
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: app
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ env.FIREBASE_PROJECTID }}
